name: Build and deploy workflow
on:
  pull_request:
  push:
    branches: master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t frameboo/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN}} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push frameboo/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build_and_push
#    env:
#      DB_USER: ${{ secrets.DB_USER }}
#      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#      DB_NAME: ${{ secrets.DB_NAME }}
#      DB_ENGINE: ${{ secrets.DB_ENGINE }}
#      SECRET_KEY: ${{ secrets.SECRET_KEY }}
#      SOCIAL_AUTH_VK_OAUTH2_KEY: ${{ secrets.SOCIAL_AUTH_VK_OAUTH2_KEY }}
#      SOCIAL_AUTH_VK_OAUTH2_SECRET: ${{ secrets.SOCIAL_AUTH_VK_OAUTH2_SECRET }}
#
#    steps:
#      - name: clone code
#        uses: actions/checkout@v2
#      - name: render config
#        run: |
#          mkdir deploy
#          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
#          cat .env-ci | envsubst > deploy/.env
#      - name: copy files to server
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          source: "deploy/docker-compose.yaml,deploy/.env"
#          target: "todolist_ci"
#          strip_components: 1
#      - name: deploy app
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          script: |
#            cd todolist_ci
#            echo ${{ secrets.PASSWORD }} | sudo -S docker-compose down
#            echo ${{ secrets.PASSWORD }} | sudo -S docker-compose up -d
